extends RefCounted
class_name FigureFactory
## The single entry point for "give me a character body".
##
## Two implementations now exist:
##
##   SkinnedFigure   — one rigged, skinned mesh (assets/characters/rig/pilgrim.glb,
##                     generated by tools/scene_gen/gen_pilgrim_rig.py). Real
##                     deformation at every joint, cloth that follows the legs,
##                     bones for the face, 7 surfaces on one mesh.
##   HumanoidFigure  — ~20 rigid mesh primitives assembled in code. No external
##                     asset, no skeleton, cheapest possible.
##
## Every call site in the project goes through here rather than naming one of
## them, so the choice can be made per build without touching gameplay code:
##
##   * the rigged model missing (a fresh checkout, or an artist mid-swap)
##     -> primitives, silently;
##   * the low render tier (web / mobile) -> primitives, because a skeleton per
##     NPC across 42 markers is the wrong trade in a browser;
##   * everything else -> skinned.
##
## Force one or the other with FORCE for A/B comparison.

## "" = auto, "skinned", "primitive"
const FORCE := ""

static var _logged := false


## Build a character body. Signature is identical to HumanoidFigure.make().
##   name    selects the CharacterPalette entry
##   height  total height in metres
##   mover   the Node3D whose world motion drives the gait (null => idle)
##   tint    seeds characters that have no palette table entry
##   is_foe  the menacing emissive look
static func make(name: String, height: float = 2.0, mover: Node3D = null,
		with_shadow: bool = true, tint: Color = Color(1, 1, 1),
		is_foe: bool = false) -> Node3D:
	if use_skinned():
		var fig := SkinnedFigure.make(name, height, mover, with_shadow, tint, is_foe)
		if fig != null:
			return fig
		# Model present but failed to instantiate — fall through rather than
		# leaving a chapter with invisible people.
	return HumanoidFigure.make(name, height, mover, with_shadow, tint, is_foe)


static func use_skinned() -> bool:
	if FORCE == "skinned":
		return true
	if FORCE == "primitive":
		return false
	if QualityTier.is_low():
		return false
	return SkinnedFigure.available()


## One-line description for the debug overlay / logs.
static func describe() -> String:
	return "figures=%s (%s)" % [
		"skinned" if use_skinned() else "primitive", QualityTier.describe()]


## Called once at startup so the chosen path is visible in the log without
## anyone having to guess which figure they are looking at.
static func log_once() -> void:
	if _logged:
		return
	_logged = true
	print("[FigureFactory] ", describe())
