extends RefCounted
class_name MaterialKit
## PBR material factory with painterly tuning.
##
## A small library of named surfaces (stone, wood, grass, gold, ...). Each maps
## to a PBR texture set under res://assets/textures/pbr/<surface>_{albedo,
## normal,rough,ao}.png (loaded via AssetLib, generated by tools/gen_pbr.py).
##
## Like the rest of the asset layer this degrades gracefully: any missing map is
## simply skipped, so a surface with no textures present is still a clean,
## palette-tinted flat material. Speculars are deliberately subdued and tints
## blended so lit geometry reads as painted form rather than glossy plastic.

# preset -> { color, rough, metallic, specular, normal_scale, uv_scale,
#             triplanar, foliage, transparent, alpha, tex }
const SURFACES := {
	"stone": {"color": Color(0.52, 0.51, 0.50), "rough": 0.92, "uv_scale": 0.5, "triplanar": true},
	"mossy_stone": {"color": Color(0.44, 0.47, 0.39), "rough": 0.94, "uv_scale": 0.5, "triplanar": true},
	"cobble": {"color": Color(0.46, 0.44, 0.42), "rough": 0.9, "uv_scale": 0.7, "triplanar": true},
	"marble": {"color": Color(0.86, 0.85, 0.83), "rough": 0.32, "specular": 0.5, "uv_scale": 0.5, "triplanar": true},
	"gold": {"color": Color(1.0, 0.82, 0.4), "rough": 0.3, "metallic": 0.85, "specular": 0.7, "uv_scale": 0.6},
	"mud": {"color": Color(0.31, 0.25, 0.19), "rough": 0.55, "specular": 0.45, "uv_scale": 0.6, "triplanar": true},
	"grass": {"color": Color(0.33, 0.5, 0.25), "rough": 0.95, "uv_scale": 0.8, "triplanar": true},
	"dry_earth": {"color": Color(0.55, 0.45, 0.31), "rough": 0.96, "uv_scale": 0.7, "triplanar": true},
	"sand": {"color": Color(0.71, 0.62, 0.44), "rough": 0.96, "uv_scale": 0.7, "triplanar": true},
	"wood": {"color": Color(0.45, 0.31, 0.19), "rough": 0.78, "uv_scale": 0.6},
	"bark": {"color": Color(0.31, 0.23, 0.17), "rough": 0.93, "uv_scale": 0.8, "triplanar": true},
	"brick": {"color": Color(0.95, 0.90, 0.88), "rough": 0.9, "uv_scale": 0.7, "triplanar": true},
	"rooftile": {"color": Color(0.96, 0.92, 0.90), "rough": 0.86, "uv_scale": 1.0, "triplanar": true},
	"ash": {"color": Color(0.22, 0.21, 0.22), "rough": 0.95, "uv_scale": 0.6, "triplanar": true},
	"cloth": {"color": Color(0.5, 0.3, 0.3), "rough": 0.95, "uv_scale": 0.7},
	"foliage": {"color": Color(0.3, 0.5, 0.25), "rough": 0.9, "foliage": true, "uv_scale": 1.0},
	"water": {"color": Color(0.2, 0.31, 0.36), "rough": 0.06, "specular": 0.6, "transparent": true, "alpha": 0.78, "uv_scale": 0.3, "tex": "water"},
}


## Build a painterly PBR material for a named surface.
## tint blends the preset colour toward `tint` by opts.tint_blend (default 0.45);
## pass Color(1,1,1) to keep the preset colour untouched.
static func make(surface: String, tint: Color = Color(1, 1, 1), opts: Dictionary = {}) -> StandardMaterial3D:
	var p: Dictionary = SURFACES.get(surface, SURFACES["stone"])
	var m := StandardMaterial3D.new()

	var realistic := RenderConfig.is_realistic()
	var base: Color = p.get("color", Color(0.5, 0.5, 0.5))
	# Photoreal mode lets the texture dominate (small tint nudge); oil mode keeps
	# the stronger painterly tint blend.
	var blend: float = float(opts.get("tint_blend", 0.18 if realistic else 0.45))
	var col: Color = base
	if not (is_equal_approx(tint.r, 1.0) and is_equal_approx(tint.g, 1.0) and is_equal_approx(tint.b, 1.0)):
		col = base.lerp(tint, blend)
	m.albedo_color = col

	m.roughness = float(opts.get("roughness", p.get("rough", 0.9)))
	m.metallic = float(opts.get("metallic", p.get("metallic", 0.0)))
	# Dielectric default closer to physical (0.5) in realistic mode.
	m.metallic_specular = float(opts.get("specular", p.get("specular", 0.5 if realistic else 0.35)))

	var texname: String = String(opts.get("tex", p.get("tex", surface)))
	var alb := AssetLib.pbr(texname, "albedo")
	if alb != null:
		m.albedo_texture = alb
		# The new PBR albedo already carries the surface's true colour. In
		# realistic mode keep albedo_color near white so the texture is NOT
		# multiplied down into mud by the preset/tint colour (just a light nudge
		# toward the gameplay tint for per-instance variety).
		if realistic:
			m.albedo_color = Color(1, 1, 1).lerp(col, 0.25)
	var nrm := AssetLib.pbr(texname, "normal")
	if nrm != null:
		m.normal_enabled = true
		m.normal_texture = nrm
		m.normal_scale = float(opts.get("normal_scale", p.get("normal_scale", 1.0)))
	var rgh := AssetLib.pbr(texname, "rough")
	if rgh != null:
		m.roughness_texture = rgh
	var ao := AssetLib.pbr(texname, "ao")
	if ao != null:
		m.ao_enabled = true
		m.ao_texture = ao

	var scale: float = float(opts.get("uv_scale", p.get("uv_scale", 1.0)))
	m.uv1_scale = Vector3(scale, scale, scale)
	if bool(opts.get("triplanar", p.get("triplanar", false))):
		m.uv1_triplanar = true

	if bool(p.get("foliage", false)):
		m.cull_mode = BaseMaterial3D.CULL_DISABLED
		m.rim_enabled = true
		m.rim = 0.4
		m.rim_tint = 0.3

	if bool(p.get("transparent", false)):
		m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		m.albedo_color.a = float(opts.get("alpha", p.get("alpha", 0.8)))

	var em: float = float(opts.get("emission", 0.0))
	if em > 0.0:
		m.emission_enabled = true
		m.emission = m.albedo_color
		m.emission_energy_multiplier = em

	return m
