#!/usr/bin/env python3
"""Write lightweight placeholder SFX (short synthesized tones: ding / click /
thud / blip / pop / coin / chime) for every SFX the game references but does not
have yet, so AudioManager.play_sfx() always finds an audible file. Real sounds
are never overwritten.

The referenced SFX list is parsed from scripts/core/AudioManager.gd, so it stays
in sync. Files this script writes are tracked in a sidecar (.placeholders.json);
--force only refreshes those, never your real audio.

Usage:
    python3 tools/gen_silent_sfx.py            # fill only missing files
    python3 tools/gen_silent_sfx.py --force    # also refresh existing placeholders
    python3 tools/gen_silent_sfx.py --list     # print referenced SFX names

The tones are tiny Ogg Vorbis blobs embedded below (made with ffmpeg). No
external tools needed to run this script.
"""
import argparse
import base64
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SFX_DIR = os.path.join(ROOT, "assets", "audio", "sfx")
AUDIO_GD = os.path.join(ROOT, "scripts", "core", "AudioManager.gd")
SIDECAR = os.path.join(SFX_DIR, ".placeholders.json")
SFX_CONFIG = os.path.join(ROOT, "assets", "audio", "sfx_config.json")

TONES = {
    "tick": (
        "T2dnUwACAAAAAAAAAAAwRuYeAAAAAPHu0ZgBHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAAMEbmHgEAAABAxUTdDkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABFYKAAAAAAAAMEbmHgIAAAA5W2OeBR45NVQVBNN3Efor+2EGhFJCbrHFiSaaKI6O"
        "4ziO4zgWSUQE+pddMg8p3dXfg/DeAkDrAAAAAIQCAAAAoN/vg//bEqJo+7bJxm6OE75dMb50"
        "e6Qe1zUJIJhIAA0A3lfd1bvUcg1VvGdfHWgNAAAACIgIRQAAAPgmAUDIW4XATs+3AVgkDQlg"
        "CGjABAoAaJhAAwAeJ/3iJ4m+q/890y4CB7DjNHv1h0rSOwgBAkIBAEBsex3H/7afOtIsFAoC"
        "gGo1felXv/aRenmcZWRkp41jgY7ks8AB1zk+w20EPHBO6KAAYAJ0aABeJ/3vKF+6AG4ACgAA"
        "AAAAAABOHwI="
    ),
    "ding": (
        "T2dnUwACAAAAAAAAAACRrkZtAAAAAKglS2EBHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAAka5GbQEAAADXEZcBDkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABHQiAAAAAAAAka5GbQIAAAAASEfNCyA2KiwuMjhBUEoSzFIoFw3/StZ1DYS2xNu8"
        "4kQTTTTRRNHRcRzHcYpFbAL6l+3j08+wUr5h87Pn6Ak8GGPo64cPR8L4uwUAAIAAAAAAANij"
        "vXjeqTZR4m47GQ1orQEgWQB+qJ0eL79DEGLgvdeRC9QJAAAAAAIAAAAAsC8BAAA/Xs8J9vRk"
        "GQAAmABemJ0eL39DEGLgfdaRB6gTAAAAAAQAoAAAAF8AAMDwnZGCDc+O7AIAAB00AB6IHR9v"
        "v0OFkJP03uvICxBhAAAAAAIAoAAAOA8AAOzfl81gD7wZAAAACTABdADeZ50eL79DpdAFvnsb"
        "eQAiDAAAAEAIAAoFAMCzAABgmGCCWMTeo+sAAIDF5BZgoQIAC55HnR5Pv0NU6Ql/e45cVyAa"
        "AAAAKCIEKAIAoAcAYA4PCylqds8lAABA0SDMdS4ATNgJMKED+AUBXiedHi+/g12JSfrZU+R1"
        "A9EAAACgg4gIBQCKAAC9vl4K+WBECgAAeHTALwDZPT37uNbgwQbwEIA2gQVgOwAdMAFeJz1u"
        "d/ELlpXa/NhDkSsFYtyPGgBARNIGAoCDiAgBAFT+VBUAAICCICAFAgDOJWEwcv4XdWSuXILF"
        "JoOtm20qMOFB0DoAChpYIIBD8IAGAF4n/e8ofr0rS8BewoMWnHsCAIhIHIRCgCIAwJqcz9Yi"
        "AAAAwHB4tjwZgHX/WgxnYhTpJLVjruacJ3tkKLBDYFs7LwCQSJgAeEACXif97yxfugBuAAAA"
        "AAAAAAAA"
    ),
    "chime": (
        "T2dnUwACAAAAAAAAAADAUDZUAAAAADg5MK0BHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAAwFA2VAEAAADApcNKDkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABOYlAAAAAAAAwFA2VAIAAAB0UlmECyI1JCQlJioxM0E8rNJVKxSD+XclJ+0MhPxa"
        "71qzc6KJJppoosnoeDKO4zgWJhqYdc+vz4VLldfueIv/IGznBM4BHl1CVAAAAAAAALr8wst7"
        "AISYwIy+Hvvj+eVjdY9pWOgAfqitz/dXuNX4irxFsRkgCgAAAAAAAAAAAAD44wDABgDrvrMZ"
        "XpiNz++vqtT4ynFEMfsARAEAAAAAAAAAAAAA/wAAAYAQxh0EHogtj/dHuNb4inyLYjNAFAAA"
        "AAAAAEAAAAAAL5wAYAFAMzKsA/53jc/vr1Ct8coJWxSbD0AUAAAAAAAAACgAAEA9AEBIAKq6"
        "KxYAvleNz59PElL7tdsURTFAFAAAAAAACBAKAADwLAAAADru9wQkwiIAUAAkfieNj5+vEVL7"
        "K7cpighAFAAAAAAECIgIBQAA+AkAAABlv/vQAQHAogZYADoF8DoAD14nrc/vbxJS+yu3KZsA"
        "RAEAAABAgICIUAAAgE8AAAAE/i6FDh5gghKVbPcQ4KHAsliABF4nXe8PfXPROq+wZWeAGADs"
        "x5cAIjIFEREKAAAAgIccAVBel9IoFYGq8NaRR3ILiC4BAQsmoINGAhoABaDpCgAFXif92i7f"
        "bGm1a19bXN4CxABgPBwQaEQoFAoBAACiLZYrQPKdIIHa6mqehQn0h7rFBBoA0OFOAAoTwMMC"
    ),
    "thud": (
        "T2dnUwACAAAAAAAAAAAXjdOWAAAAALxh9tMBHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAAF43TlgEAAADQfvKCDkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABFgpAAAAAAAAF43TlgIAAABmfNK6DB5lKiwsMDpESkxDJSTTay60Kb//IIAgaLvz"
        "zooTTTRRXIyOFiI6LqaYBDqa/V/nOewC2AB1FgBAVogQAAQAAN0/1Q8A7ECPvcWPu0TRzK9/"
        "hxPwT7SoHmgq5OqsvzXTr9b0XcTi4m0uvDXTr9b0XcRidLV0rCPV37Sm7yIWx1vVHwpbJGoM"
        "CnyCBRYAOiYA3qr9f+21tF0UsIHWAAAQAkIBAAAAgJcAAFO9rwMAAAATmASNTRqCwgMLnpr9"
        "f++1tF0lsIHWAAAQAiIAAAAA8DsAwOrpDwsAAEAHJkJnk8Z1gAcEWACeiv3/7DW2C+AArQEA"
        "IAQoAgAgAADwPQDATvbLAAAAQEcyBDqSxlPQwAMdAF56/f/3GjsVsIHWAAAQEaEAQAAA4NcC"
        "AJaTrywAAAAT6EADOj2Lxkd3DTyAB3SgA15a/X921NgugAO0BgAAAUZEAAEBAPgBADDpfBkA"
        "AIDgMeWzp024I8sozchfChxA8wkkeAAaMAE0FAA+Ov1/js+S6IKBLTVQNwAAhBkRAhQBAPgC"
        "AND//w0AAABMYIitcc8lVjsCjkfNZnsb+u1cw2GaOtAsgAYoABPooAAFAP4p/X/OzpreFA0b"
        "oG4AAEhxERERAIBXAACt3vMAAAAUOiW4ftKPgw5sQnfKkFuaQ67P/mND9/LCsWwXiQerAVgS"
        "AG6BAjABHRMAvin9f84uJbMrYAPUDQAAjUdERCgA+AIAYJbuAQAAHQEkk68yBM1msFIDpB9y"
        "MU5hZON8K6PcJtOoPrQ1BhawQAANNExAAxqY4AHAAv4o/X9Ot9LQVQG7GGjj/3ECADCMiBAQ"
        "AQCg1wAAABPJBBYYgxqBguSMuAlEeVNM5KR9K6WvrhMAGh4AGpDoGoAOWACeJ/3ntrR0NcAG"
        "WrFP0wCAQgBQAAAAAFAmSQexxGMJYFBwCwAL"
    ),
    "blip": (
        "T2dnUwACAAAAAAAAAAABlOGkAAAAAA+RzGgBHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAAAZThpAEAAAAeWPaaDkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABMgNAAAAAAAAAZThpAIAAAASSTEwBSE8KDlHrFIoJ+nq894yzjwDQThny6nX7Pul"
        "fmmizujJ6Imi4zgl+oet90/f/4MwmmaK0QkPMJzHB+ecAPGVBIgKAICAAAoAAKqNcHzW5kRi"
        "HRr/BtXS5wospkEBoAEmgMUD/ncdH2+/II3ys2KL0Z8AUQAAAAAAAoACAAAA5wXggAA439MH"
        "ADSgA14nnR4vv6CM8rNSthj6fEA0AAAAABEREQAAvgQAMgASiPdf7hQAHUxQADp8gwR0AKxg"
        "ASygYU5gAj4nfW5338A+4dm7HTGQQMtKwDlAXAhQKAAACsCymm+fJrdmZ1CJAADJxT/5fB8D"
        "cCDCi3yq0/QCvxeV1C1OmQBObzmBBh4A"
    ),
    "pop": (
        "T2dnUwACAAAAAAAAAABJadsxAAAAAAz5lUYBHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAASWnbMQEAAAAlpiT3DkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABFYKAAAAAAAASWnbMQIAAAANRmP/BR5JOVoVxNLVoClbuq4DCII1Gnu4s1/qXOqc"
        "KHoyjuM4joUA+odd2V3Ca6r/ROrPBqiHjX744ImkxwAAAAACIwIIAAA86vrXkpg1xn80XwGA"
        "LZ6LcBxCFAGARxQRswzn7MrgWgF0wAQKoAH8Ap5H3a93PwOqtxfqd+PKth+3qgAAAAiIiAgF"
        "YFkWAAAAALb39dHb4ARQBw26B3TgASDhwQJggnwAAj4n/RhXPwC7vq85dgls4+sTAMA2iAhF"
        "AAVgTawCAgAAdtxf//jw4+YcE+h7k2L9TuP17b0jU70brlARi7PEaXt734utF8MzhPKjiqzC"
        "EA3AoOgAHgVgAsCEB14n/e8sX7oAbgACAAAAAAAA4GLDAA=="
    ),
    "coin": (
        "T2dnUwACAAAAAAAAAACYsMq3AAAAAIjM3BcBHgF2b3JiaXMAAAAAAUSsAAAAAAAAcBEBAAAA"
        "AAC4AU9nZ1MAAAAAAAAAAAAAmLDKtwEAAAC34T81DkH///////////////8RA3ZvcmJpcw0A"
        "AABMYXZmNTguNzYuMTAwAQAAACAAAABlbmNvZGVyPUxhdmM1OC4xMzQuMTAwIGxpYnZvcmJp"
        "cwEFdm9yYmlzIkJDVgEAQAAAJHMYKkalcxaEEBpCUBnjHELOa+wZQkwRghwyTFvLJXOQIaSg"
        "QohbKIHQkFUAAEAAAIdBeBSEikEIIYQlPViSgyc9CCGEiDl4FIRpQQghhBBCCCGEEEIIIYRF"
        "OWiSgydBCB2E4zA4DIPlOPgchEU5WBCDJ0HoIIQPQriag6w5CCGEJDVIUIMGOegchMIsKIqC"
        "xDC4FoQENSiMguQwyNSDC0KImoNJNfgahGdBeBaEaUEIIYQkQUiQgwZByBiERkFYkoMGObgU"
        "hMtBqBqEKjkIH4QgNGQVAJAAAKCiKIqiKAoQGrIKAMgAABBAURTHcRzJkRzJsRwLCA1ZBQAA"
        "AQAIAACgSIqkSI7kSJIkWZIlWZIlWZLmiaosy7Isy7IsyzIQGrIKAEgAAFBRDEVxFAcIDVkF"
        "AGQAAAigOIqlWIqlaIrniI4IhIasAgCAAAAEAAAQNENTPEeURM9UVde2bdu2bdu2bdu2bdu2"
        "bVuWZRkIDVkFAEAAABDSaWapBogwAxkGQkNWAQAIAACAEYowxIDQkFUAAEAAAIAYSg6iCa05"
        "35zjoFkOmkqxOR2cSLV5kpuKuTnnnHPOyeacMc4555yinFkMmgmtOeecxKBZCpoJrTnnnCex"
        "edCaKq0555xxzulgnBHGOeecJq15kJqNtTnnnAWtaY6aS7E555xIuXlSm0u1Oeecc84555xz"
        "zjnnnOrF6RycE84555yovbmWm9DFOeecT8bp3pwQzjnnnHPOOeecc84555wgNGQVAAAEAEAQ"
        "ho1h3CkI0udoIEYRYhoy6UH36DAJGoOcQurR6GiklDoIJZVxUkonCA1ZBQAAAgBACCGFFFJI"
        "IYUUUkghhRRiiCGGGHLKKaeggkoqqaiijDLLLLPMMssss8w67KyzDjsMMcQQQyutxFJTbTXW"
        "WGvuOeeag7RWWmuttVJKKaWUUgpCQ1YBACAAAARCBhlkkFFIIYUUYogpp5xyCiqogNCQVQAA"
        "IACAAAAAAE/yHNERHdERHdERHdERHdHxHM8RJVESJVESLdMyNdNTRVV1ZdeWdVm3fVvYhV33"
        "fd33fd34dWFYlmVZlmVZlmVZlmVZlmVZliA0ZBUAAAIAACCEEEJIIYUUUkgpxhhzzDnoJJQQ"
        "CA1ZBQAAAgAIAAAAcBRHcRzJkRxJsiRL0iTN0ixP8zRPEz1RFEXTNFXRFV1RN21RNmXTNV1T"
        "Nl1VVm1Xlm1btnXbl2Xb933f933f933f933f931dB0JDVgEAEgAAOpIjKZIiKZLjOI4kSUBo"
        "yCoAQAYAQAAAiuIojuM4kiRJkiVpkmd5lqiZmumZniqqQGjIKgAAEABAAAAAAAAAiqZ4iql4"
        "iqh4juiIkmiZlqipmivKpuy6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6ruu6rguE"
        "hqwCACQAAHQkR3IkR1IkRVIkR3KA0JBVAIAMAIAAABzDMSRFcizL0jRP8zRPEz3REz3TU0VX"
        "dIHQkFUAACAAgAAAAAAAAAzJsBTL0RxNEiXVUi1VUy3VUkXVU1VVVVVVVVVVVVVVVVVVVVVV"
        "VVVVVVVVVVVVVVVVVVVVVU3TNE0TCA1ZCQAAAQDAHITOLaiQSQktmIooxCToUkEHKejOMIKg"
        "9xI5g5zHFDlCkMaWSYSYBkJDVgQAUQAAgDHIMcQccs5R6iRFzjkqHaXGOUepo9RRSrGmGDNK"
        "JbZUa+Oco9RR6iilGkuLHaUUY4qxAACAAAcAgAALodCQFQFAFAAAgRBSCimFlGLOKeeQUsox"
        "5hxSijmnnFPOOSidlMo5Jp2TEimlnGPOKeeclM5J5ZyT0kkoAAAgwAEAIMBCKDRkRQAQJwDg"
        "cBzNkzRNFCVNE0VPFF3VE0XVlTTNNDVRVFVNFE3VVFVZFk3VlSVNM01NFFVTE0VVFVVTlk1V"
        "lWXPNG3ZVFXdFlVVt2Vb9m1XlnXfM03ZFlXV1k1VtXVXlnXdlW3dlzTNNDVRVFVNFFXXVFVb"
        "NlXVtjVRdF1RVWVZVFVZdmXXtlVX1nVNFF3XU03ZFVVVllXZ1WVVlnVfdFVdV13X11VX9n3Z"
        "1n1d1nVhGFXV1k3X1XVVdnVf1m3fl3VdWCZNM01NFF1VE0VVNVXVtk1VlW1NFF1XVFVZFk3V"
        "lVXZ9XXVdW1dE0XXFVVVlkVVlV1VdnXflWXdFlVVt1XZ9XVTdXVdtm1jmG1bF05VtXVVdnVh"
        "lV3dl3XbGG5d943NNG3bdF1dN11X121dN4ZZ131fVFVfV2XZN1ZZ9n3d97F13xhGVdV1U3aF"
        "X3VlX7h1X1luXee8to1s+8ox674z/EZ0XziW1bYpr24Lw6zr+MLuLLvwKz3TtHXTVXXdVF1f"
        "l21bGW5dR1RVX1dlWfhNV/aFW9eN49Z9Zxldl67Ksi+ssqwMt+8bw+77wrLatnHMto5r68qx"
        "+0pl95VleG3bV2ZdJ8y6bRy7rzN+YUgAAMCAAwBAgAlloNCQFQFAnAAAg5BziCkIkWIQQggp"
        "hRBSihiDkDknJWNOSikltVBKahFjECrHpGTOSQmltBRKaSmU0lopJbZQSouttVpTa7GGUloL"
        "pbRYSmkxtVZja63GiDEJmXNSMueklFJaK6W0ljlHpXOQUgchpZJSiyWlGCvnpGTQUekgpFRS"
        "iamkFGMoJcaSUowlpRpbii23GHMOpbRYUomxpBRjiynHFmPOEWNQMuekZM5JKaW0VkpqrXJO"
        "SgchpcxBSSWlGEtJKWbOSeogpNRBR6mkFGNJKbZQSmwlpRpLSTG2GHNuKbYaSmmxpBRrSSnG"
        "FmPOLbbcOgithVRiDKXE2GLMubVWayglxpJSrCWl2mKstbcYcw2lxFhSqbGkFGursdcYY80p"
        "tlxTizW3GHuuLbdecw4+tVZziinXFmPuMbcga869dxBaC6XEGEqJscVWa4sx51BKjCWlGktJ"
        "sbYYc22t1h5KibGkFGtJqcYYY86xxl5Ta7W2GHtOLdZcc+69xhyDaq3mFmPuKbaca66919yC"
        "LAAAYMABACDAhDJQaMhKACAKAAAwhjHnIDQKOeeclAYp55yTkjkHIYSUMucghJBS5xyEklrr"
        "nINQSmullJRai7GUklJrMRYAAFDgAAAQYIOmxOIAhYasBABSAQAMjmNZnmeaqmrLjiV5niiq"
        "pqvqtiNZnieKqqqqtm15nimqqqq6rq5bnieKqqq6rqvrnmmqqqq6rizrvmeaqqqqrivLvm+q"
        "quu6rizLsvCbquq6rivLsu0Lq+vKsizbtm4bw+q6sizLtm3rynHruq77vrEcR7au+7ow/MZw"
        "JAAAPMEBAKjAhtURTorGAgsNWQkAZAAAEMYgZBBSyCCEFFJIKYSUUgIAAAYcAAACTCgDhYas"
        "BACiAAAAIqy11lpjrbXWWoustdZaa62llFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSiml"
        "lFIBAFITDgBSDzZoSiwOUGjISgAgFQAAMIYpphyDDDrDlHPQSSglpYYx55yDklJKlXNSSkmp"
        "tdYy56SUklJrMWYQUmktxhprzSCUlFqMMfYaSmktxlpzzz2U0lqLtdbcc2ktxhx7z0EIk1Kr"
        "teYchA6qtVprzjn4IExrsdYadBBCGACA0+AAAHpgw+oIJ0VjgYWGrAQAUgEACISUYswx55xD"
        "SjHmnHPOOYeUYswx55xzTjHGnHPOQQihYswx5yCEEELmnHPOQQghhMw555yDEEIInXMOQggh"
        "hBA65yCEEEIIIXQOQgghhBBC6CCEEEIIIYTQQQghhBBCCKGDEEIIIYQQQgEAgAUOAAABNqyO"
        "cFI0FlhoyEoAAAgAAILaciwxM0g55iw2BCEFuVVIKcW0ZkYZ5bhVCiGkNGROMWSkxFpzqRwA"
        "AACCAAABIQEABggKZgCAwQHC5yDoBAiONgAAQYjMEImGheDwoBIgIqYCgMQEhVwAqLC4SLu4"
        "gC4DXNDFXQdCCEIQglgcQAEJODjhhife8IQbnKBTVOogAAAAAAAMAOABAOC4ACIimsPI0Njg"
        "6PD4AAkJAAAAAAAYAPgAADhEgIiI5jAyNDY4Ojw+QEICAAAAAAAAAACAgIAAAAAAAEAAAACA"
        "gE9nZ1MABPMSAAAAAAAAmLDKtwIAAACC9RiPByAzKis7TyCkUig5C3+lrK9qIPTlwnjFiSaa"
        "aKKJJpoojuM4FnESJjqYnS9Pv/9LCONNOiLyeIAeIxljgH+cAwAFAAAAAAAAgNb8p5IXRuy2"
        "tTZT839NgDYoAF6oXe5PP/+FKv8PaQv3gGgAAAAAgAIAAABgfiQArFM66xbC574FEgAoAP53"
        "Xe5PP8NHL7wpW5gNRAMAAAAAFEAAAAAwPxIAOD5ubCB8/u0hAYACABpeJ53vTz/DM6r8v/nb"
        "okcA0QAAAEBAREQoAMAtAOD4OFjg5EO2BAAUABJAGoAFBAg0eGhAggkWCACjAD4n3V4v4ntk"
        "5e/raU/Rr2Gbob86AQB6CiIUIUABMFvgpZ8XAABxdDxdCr9e14Os7hiEtE0S3mH6HaSQvB+N"
        "xQL7LNAMwQQIgAYawMQDNABeJ/3vKF+6AG6ACjC2AQAAAAAAAEBJfvNcz+SlJhcAFg=="
    )
}

SFX_TONE = {
    "ui_select": "tick", "interact": "tick", "save": "tick",
    "quest_complete": "ding", "blessing": "ding", "cross_grace": "ding",
    "promise": "ding", "chapel_kneel": "ding", "lantern_word": "ding",
    "river_cross": "ding", "vanity_lay_down": "ding",
    "victory": "chime", "mention": "chime",
    "collapse": "thud", "burden_fall": "thud", "sleep_fail": "thud",
    "shadow_snuff": "thud",
    "message_in": "blip", "sticker_send": "pop", "vanity_buy": "coin",
}
DEFAULT_TONE = "tick"


def referenced():
    names = set()
    if os.path.exists(AUDIO_GD):
        for line in open(AUDIO_GD, encoding="utf-8"):
            if "assets/audio/sfx/" in line and ".ogg" in line:
                seg = line.split("assets/audio/sfx/", 1)[1].split(".ogg", 1)[0]
                if seg and all(c.isalnum() or c == "_" for c in seg):
                    names.add(seg)
    return sorted(names)


def _load_sidecar():
    if os.path.exists(SIDECAR):
        try:
            return set(json.load(open(SIDECAR, encoding="utf-8")))
        except Exception:
            return set()
    return set()


def _tone_overrides():
    out = {}
    if os.path.exists(SFX_CONFIG):
        try:
            data = json.load(open(SFX_CONFIG, encoding="utf-8"))
            for k, v in data.get("sfx", {}).items():
                if isinstance(v, dict) and v.get("tone"):
                    out[k] = v["tone"]
        except Exception:
            pass
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true",
                    help="refresh existing placeholders (never touches real audio)")
    ap.add_argument("--list", action="store_true", help="just print referenced names")
    args = ap.parse_args()

    names = referenced()
    if args.list:
        print(chr(10).join(names))
        return

    blobs = {k: base64.b64decode(v) for k, v in TONES.items()}
    os.makedirs(SFX_DIR, exist_ok=True)
    placeholders = _load_sidecar()
    overrides = _tone_overrides()
    n = 0
    for nm in names:
        out = os.path.join(SFX_DIR, nm + ".ogg")
        exists = os.path.exists(out)
        if exists and not (args.force and nm in placeholders):
            continue
        tone = overrides.get(nm, SFX_TONE.get(nm, DEFAULT_TONE))
        if tone not in blobs:
            tone = DEFAULT_TONE
        open(out, "wb").write(blobs[tone])
        placeholders.add(nm)
        n += 1
        print("wrote %s.ogg  (%s)" % (nm, tone))
    json.dump(sorted(placeholders), open(SIDECAR, "w", encoding="utf-8"))
    print("wrote %d tone placeholder(s) into %s" % (n, SFX_DIR))


if __name__ == "__main__":
    main()
